# Generated by Django 5.2.9 on 2026-01-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscriptionplan_tenantpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='grace_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
