# Generated by Django 5.2.9 on 2025-12-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='User', max_length=255, null=True)),
                ('action', models.CharField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_info', models.CharField(blank=True, default='Customer', max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, default='Product', max_length=255, null=True)),
                ('product_specification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('changes_on_update', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
