"""
Django settings for multi_caffe_management project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1+wss@qj54==i6=5*q^icmjuur@ss*4ls2pm#gzbiihwih94rv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*.cafe.pootechnologies.tech", ".cafe.pootechnologies.tech", "cafe.pootechnologies.tech", "45.93.136.48"]


# Application definition

SHARED_APPS = [
    'django_tenants',
    'tenants.apps.TenantsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tenant_users.permissions',
    'tenant_users.tenants',
    'corsheaders',
]

TENANT_APPS = [
    "django.contrib.auth",  # new
    "django.contrib.contenttypes",  # new
    "tenant_users.permissions",  # new
    "inventory.apps.InventoryConfig",
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenant_users.tenants.middleware.TenantAccessMiddleware',  # must be right here
    # ...
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE += [
    "tenants.middleware.TenantPaymentRequiredMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True 
ROOT_URLCONF = 'multi_caffe_management.urls'

PUBLIC_SCHEMA_URLCONF = 'multi_caffe_management.urls_public'
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multi_caffe_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# 1. Parse the Render URL
# DATABASES = {
#     'default': dj_database_url.parse(config('DATABASE_URL'))
# }

# # 2. OVERRIDE the engine to use django-tenants (Crucial Step)
# DATABASES['default']['ENGINE'] = 'django_tenants.postgresql_backend'

# # 3. Set SSL options for Render
# DATABASES['default']['OPTIONS'] = {
#     'sslmode': 'require',
# }

DATABASES = {
    'default': {
        "ENGINE": "django_tenants.postgresql_backend",
        'NAME': os.environ.get('DB_NAME', 'your_local_db_name'),
        'USER': os.environ.get('DB_USER', 'your_local_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'your_local_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        # 'OPTIONS': {
        #     'charset': 'utf8mb4',
        #     'init_command': "SET NAMES 'utf8mb4'",
        # },
    }
}



# new
DATABASE_ROUTERS = [
    "django_tenants.routers.TenantSyncRouter",
]

BASE_DOMAIN = "cafe.pootechnologies.tech"
PUBLIC_SCHEMA_NAME = "public"


# TENANT_USERS_DOMAIN defines from which domain the users should be provisioned. This should match the domain of the public tenant.
TENANT_USERS_DOMAIN = BASE_DOMAIN

# AUTHENTICATION_BACKENDS sets a custom authentication backend that works well with tenant-level groups and permissions.
AUTHENTICATION_BACKENDS = [
    "tenant_users.permissions.backend.UserBackend",
]


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

from datetime import timedelta

REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
  ),
  'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
  'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
  'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
  'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# chapa settings for testing
CHAPA_PUBLIC_KEY = "CHAPUBK_TEST-V6GJI42oSMRKHrkQgP5P8gH2I34BM3FD"
CHAPA_SECRET_KEY ="CHASECK_TEST-vrVjpSUyuzegPSk04JSpKXSWyYOy8YYm"
CHAPA_BASE_URL = "https://api.chapa.co/v1"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'


# Static files (CSS, JavaScript, Images)
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory where static files will be collected
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Additional directories to look for static files

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Where files go when collected

# Enable WhiteNoise compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
# This path is relative to the root of your project inside the Docker container
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# HTTPS Settings
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "tenants.UserAccount"
TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"
